
//GENERAL DEFINES
//---------------
#define CLOCK_PERIOD_NS					12.5																			// Clock period in nano second, 12.5 because the frequency is 80MHz (see PLL_Init())
#define PRI_QEI0								2																					// Priority or the interrupt generated by QEI0
#define PRI_QEI1								2																					// Priority or the interrupt generated by QEI1
#define PRI_PORTF 							5																					// Priority or the interrupt generated by Port F
#define PRI_PORTB 							2																					// Priority or the interrupt generated by Port B
#define PRI_SYSTICK 						5																					// Priority or the interrupt generated by SYSTICK

/*
//GENERAL DEFINES - REGISTERS
//---------------------------
#define SYSCTL_RIS_R          	(*((volatile unsigned long *)0x400FE050)) //
#define SYSCTL_RCC_R          	(*((volatile unsigned long *)0x400FE060)) //
#define SYSCTL_RCC2_R          	(*((volatile unsigned long *)0x400FE070)) //
#define SYSCTL_RCGC0_R          (*((volatile unsigned long *)0x400FE100)) //Register to enable interface/function/module clock
#define SYSCTL_RCGC1_R          (*((volatile unsigned long *)0x400FE104)) //Register to enable interface/function/module clock
#define SYSCTL_RCGC2_R          (*((volatile unsigned long *)0x400FE108)) //Register to enable interface/function/module clock
#define SYSCTL_RCGCGPIO_R				(*((volatile unsigned long *)0x400FE608)) //TO TEST //Not used Register to enable GPIO clock
#define SYSCTL_RCGCQEI_R        (*((volatile unsigned long *)0x400FE644)) //TO TEST //Not used Register to enable QEI clock

//Gates control REGISTERS
//-----------------------------------------------------
#define SYSCTL_RCGC1_R          (*((volatile unsigned long *)0x400FE104))
#define SYSCTL_RCGC2_R          (*((volatile unsigned long *)0x400FE108))*/

//PORT A DEFINES - REGISTERS, Base address: don't know, don't care
//-----------------------------------------------------
#define GPIO_PORTA_AFSEL_R      (*((volatile unsigned long *)0x40004420))
#define GPIO_PORTA_DEN_R        (*((volatile unsigned long *)0x4000451C))
#define GPIO_PORTA_AMSEL_R      (*((volatile unsigned long *)0x40004528))
#define GPIO_PORTA_PCTL_R       (*((volatile unsigned long *)0x4000452C))

//PORT B DEFINES - REGISTERS, Base address: 0x4000.5000
//-----------------------------------------------------
#define GPIO_PORTB_DATA_R				(*((volatile unsigned long *)0x400053FC)) //Offset 0x000 
#define GPIO_PORTB_DIR_R				(*((volatile unsigned long *)0x40005400)) //Offset 0x400 
#define GPIO_PORTB_IS_R					(*((volatile unsigned long *)0x40005404)) //Offset 0x404 
#define GPIO_PORTB_IBE_R				(*((volatile unsigned long *)0x40005408)) //Offset 0x408 
#define GPIO_PORTB_IEV_R				(*((volatile unsigned long *)0x4000540C)) //Offset 0x40C 
#define GPIO_PORTB_IM_R					(*((volatile unsigned long *)0x40005410)) //Offset 0x410 
#define GPIO_PORTB_RIS_R				(*((volatile unsigned long *)0x40005414)) //Offset 0x414 
#define GPIO_PORTB_MIS_R				(*((volatile unsigned long *)0x40005418)) //Offset 0x418 
#define GPIO_PORTB_ICR_R				(*((volatile unsigned long *)0x4000541C)) //Offset 0x41C 
#define GPIO_PORTB_AFSEL_R			(*((volatile unsigned long *)0x40005420)) //Offset 0x420 
#define GPIO_PORTB_DR2R_R				(*((volatile unsigned long *)0x40005500)) //Offset 0x500 
#define GPIO_PORTB_DR4R_R				(*((volatile unsigned long *)0x40005504)) //Offset 0x504 
#define GPIO_PORTB_DR8R_R				(*((volatile unsigned long *)0x40005508)) //Offset 0x508 
#define GPIO_PORTB_ODR_R				(*((volatile unsigned long *)0x4000550C)) //Offset 0x50C 
#define GPIO_PORTB_PUR_R				(*((volatile unsigned long *)0x40005510)) //Offset 0x510 
#define GPIO_PORTB_PDR_R				(*((volatile unsigned long *)0x40005514)) //Offset 0x514 
#define GPIO_PORTB_SLR_R				(*((volatile unsigned long *)0x40005518)) //Offset 0x518 
#define GPIO_PORTB_DEN_R				(*((volatile unsigned long *)0x4000551C)) //Offset 0x51C 
#define GPIO_PORTB_LOCK_R				(*((volatile unsigned long *)0x40005520)) //Offset 0x520 
#define GPIO_PORTB_CR_R					(*((volatile unsigned long *)0x40005524)) //Offset 0x524 
#define GPIO_PORTB_AMSEL_R			(*((volatile unsigned long *)0x40005528)) //Offset 0x528 
#define GPIO_PORTB_PCTL_R				(*((volatile unsigned long *)0x4000552C)) //Offset 0x52C 
#define GPIO_PORTB_ADCCTL_R			(*((volatile unsigned long *)0x40005530)) //Offset 0x530 
#define GPIO_PORTB_DMACTL_R			(*((volatile unsigned long *)0x40005534)) //Offset 0x534 
#define GPIO_PORTB_PeriphID4_R	(*((volatile unsigned long *)0x40005FD0)) //Offset 0xFD0 
#define GPIO_PORTB_PeriphID5_R	(*((volatile unsigned long *)0x40005FD4)) //Offset 0xFD4 
#define GPIO_PORTB_PeriphID6_R	(*((volatile unsigned long *)0x40005FD8)) //Offset 0xFD8 
#define GPIO_PORTB_PeriphID7_R	(*((volatile unsigned long *)0x40005FDC)) //Offset 0xFDC 
#define GPIO_PORTB_PeriphID0_R	(*((volatile unsigned long *)0x40005FE0)) //Offset 0xFE0 
#define GPIO_PORTB_PeriphID1_R	(*((volatile unsigned long *)0x40005FE4)) //Offset 0xFE4 
#define GPIO_PORTB_PeriphID2_R	(*((volatile unsigned long *)0x40005FE8)) //Offset 0xFE8 
#define GPIO_PORTB_PeriphID3_R	(*((volatile unsigned long *)0x40005FEC)) //Offset 0xFEC 

//PORT C DEFINES - REGISTERS, Base address: 0x4000.6000
//-----------------------------------------------------
#define GPIO_PORTC_DATA_R				(*((volatile unsigned long *)0x400063FC)) //Offset 0x000 
#define GPIO_PORTC_DIR_R				(*((volatile unsigned long *)0x40006400)) //Offset 0x400 
#define GPIO_PORTC_IS_R					(*((volatile unsigned long *)0x40006404)) //Offset 0x404 
#define GPIO_PORTC_IBE_R				(*((volatile unsigned long *)0x40006408)) //Offset 0x408 
#define GPIO_PORTC_IEV_R				(*((volatile unsigned long *)0x4000640C)) //Offset 0x40C 
#define GPIO_PORTC_IM_R					(*((volatile unsigned long *)0x40006410)) //Offset 0x410 
#define GPIO_PORTC_RIS_R				(*((volatile unsigned long *)0x40006414)) //Offset 0x414 
#define GPIO_PORTC_MIS_R				(*((volatile unsigned long *)0x40006418)) //Offset 0x418 
#define GPIO_PORTC_ICR_R				(*((volatile unsigned long *)0x4000641C)) //Offset 0x41C 
#define GPIO_PORTC_AFSEL_R			(*((volatile unsigned long *)0x40006420)) //Offset 0x420 
#define GPIO_PORTC_DR2R_R				(*((volatile unsigned long *)0x40006500)) //Offset 0x500 
#define GPIO_PORTC_DR4R_R				(*((volatile unsigned long *)0x40006504)) //Offset 0x504 
#define GPIO_PORTC_DR8R_R				(*((volatile unsigned long *)0x40006508)) //Offset 0x508 
#define GPIO_PORTC_ODR_R				(*((volatile unsigned long *)0x4000650C)) //Offset 0x50C 
#define GPIO_PORTC_PUR_R				(*((volatile unsigned long *)0x40006510)) //Offset 0x510 
#define GPIO_PORTC_PDR_R				(*((volatile unsigned long *)0x40006514)) //Offset 0x514 
#define GPIO_PORTC_SLR_R				(*((volatile unsigned long *)0x40006518)) //Offset 0x518 
#define GPIO_PORTC_DEN_R				(*((volatile unsigned long *)0x4000651C)) //Offset 0x51C 
#define GPIO_PORTC_LOCK_R				(*((volatile unsigned long *)0x40006520)) //Offset 0x520 
#define GPIO_PORTC_CR_R					(*((volatile unsigned long *)0x40006524)) //Offset 0x524 
#define GPIO_PORTC_AMSEL_R			(*((volatile unsigned long *)0x40006528)) //Offset 0x528 
#define GPIO_PORTC_PCTL_R				(*((volatile unsigned long *)0x4000652C)) //Offset 0x52C 
#define GPIO_PORTC_ADCCTL_R			(*((volatile unsigned long *)0x40006530)) //Offset 0x530 
#define GPIO_PORTC_DMACTL_R			(*((volatile unsigned long *)0x40006534)) //Offset 0x534 
#define GPIO_PORTC_PeriphID4_R	(*((volatile unsigned long *)0x40006FD0)) //Offset 0xFD0 
#define GPIO_PORTC_PeriphID5_R	(*((volatile unsigned long *)0x40006FD4)) //Offset 0xFD4 
#define GPIO_PORTC_PeriphID6_R	(*((volatile unsigned long *)0x40006FD8)) //Offset 0xFD8 
#define GPIO_PORTC_PeriphID7_R	(*((volatile unsigned long *)0x40006FDC)) //Offset 0xFDC 
#define GPIO_PORTC_PeriphID0_R	(*((volatile unsigned long *)0x40006FE0)) //Offset 0xFE0 
#define GPIO_PORTC_PeriphID1_R	(*((volatile unsigned long *)0x40006FE4)) //Offset 0xFE4 
#define GPIO_PORTC_PeriphID2_R	(*((volatile unsigned long *)0x40006FE8)) //Offset 0xFE8 
#define GPIO_PORTC_PeriphID3_R	(*((volatile unsigned long *)0x40006FEC)) //Offset 0xFEC 

//PORT D DEFINES - REGISTERS, Base address: 0x4000.7000
//-----------------------------------------------------
#define GPIO_PORTD_DATA_R				(*((volatile unsigned long *)0x400073FC)) //Offset 0x000 
#define GPIO_PORTD_DIR_R				(*((volatile unsigned long *)0x40007400)) //Offset 0x400 
#define GPIO_PORTD_IS_R					(*((volatile unsigned long *)0x40007404)) //Offset 0x404 
#define GPIO_PORTD_IBE_R				(*((volatile unsigned long *)0x40007408)) //Offset 0x408 
#define GPIO_PORTD_IEV_R				(*((volatile unsigned long *)0x4000740C)) //Offset 0x40C 
#define GPIO_PORTD_IM_R					(*((volatile unsigned long *)0x40007410)) //Offset 0x410 
#define GPIO_PORTD_RIS_R				(*((volatile unsigned long *)0x40007414)) //Offset 0x414 
#define GPIO_PORTD_MIS_R				(*((volatile unsigned long *)0x40007418)) //Offset 0x418 
#define GPIO_PORTD_ICR_R				(*((volatile unsigned long *)0x4000741C)) //Offset 0x41C 
#define GPIO_PORTD_AFSEL_R			(*((volatile unsigned long *)0x40007420)) //Offset 0x420 
#define GPIO_PORTD_DR2R_R				(*((volatile unsigned long *)0x40007500)) //Offset 0x500 
#define GPIO_PORTD_DR4R_R				(*((volatile unsigned long *)0x40007504)) //Offset 0x504 
#define GPIO_PORTD_DR8R_R				(*((volatile unsigned long *)0x40007508)) //Offset 0x508 
#define GPIO_PORTD_ODR_R				(*((volatile unsigned long *)0x4000750C)) //Offset 0x50C 
#define GPIO_PORTD_PUR_R				(*((volatile unsigned long *)0x40007510)) //Offset 0x510 
#define GPIO_PORTD_PDR_R				(*((volatile unsigned long *)0x40007514)) //Offset 0x514 
#define GPIO_PORTD_SLR_R				(*((volatile unsigned long *)0x40007518)) //Offset 0x518 
#define GPIO_PORTD_DEN_R				(*((volatile unsigned long *)0x4000751C)) //Offset 0x51C 
#define GPIO_PORTD_LOCK_R				(*((volatile unsigned long *)0x40007520)) //Offset 0x520 
#define GPIO_PORTD_CR_R					(*((volatile unsigned long *)0x40007524)) //Offset 0x524 
#define GPIO_PORTD_AMSEL_R			(*((volatile unsigned long *)0x40007528)) //Offset 0x528 
#define GPIO_PORTD_PCTL_R				(*((volatile unsigned long *)0x4000752C)) //Offset 0x52C 
#define GPIO_PORTD_ADCCTL_R			(*((volatile unsigned long *)0x40007530)) //Offset 0x530 
#define GPIO_PORTD_DMACTL_R			(*((volatile unsigned long *)0x40007534)) //Offset 0x534 
#define GPIO_PORTD_PeriphID4_R	(*((volatile unsigned long *)0x40007FD0)) //Offset 0xFD0 
#define GPIO_PORTD_PeriphID5_R	(*((volatile unsigned long *)0x40007FD4)) //Offset 0xFD4 
#define GPIO_PORTD_PeriphID6_R	(*((volatile unsigned long *)0x40007FD8)) //Offset 0xFD8 
#define GPIO_PORTD_PeriphID7_R	(*((volatile unsigned long *)0x40007FDC)) //Offset 0xFDC 
#define GPIO_PORTD_PeriphID0_R	(*((volatile unsigned long *)0x40007FE0)) //Offset 0xFE0 
#define GPIO_PORTD_PeriphID1_R	(*((volatile unsigned long *)0x40007FE4)) //Offset 0xFE4 
#define GPIO_PORTD_PeriphID2_R	(*((volatile unsigned long *)0x40007FE8)) //Offset 0xFE8 
#define GPIO_PORTD_PeriphID3_R	(*((volatile unsigned long *)0x40007FEC)) //Offset 0xFEC 

//PORT E DEFINES - REGISTERS, Base address: 0x4002.4000
//-----------------------------------------------------
#define GPIO_PORTE_DATA_R				(*((volatile unsigned long *)0x400243FC)) //Offset 0x000 
#define GPIO_PORTE_DIR_R				(*((volatile unsigned long *)0x40024400)) //Offset 0x400 
#define GPIO_PORTE_IS_R					(*((volatile unsigned long *)0x40024404)) //Offset 0x404 
#define GPIO_PORTE_IBE_R				(*((volatile unsigned long *)0x40024408)) //Offset 0x408 
#define GPIO_PORTE_IEV_R				(*((volatile unsigned long *)0x4002440C)) //Offset 0x40C 
#define GPIO_PORTE_IM_R					(*((volatile unsigned long *)0x40024410)) //Offset 0x410 
#define GPIO_PORTE_RIS_R				(*((volatile unsigned long *)0x40024414)) //Offset 0x414 
#define GPIO_PORTE_MIS_R				(*((volatile unsigned long *)0x40024418)) //Offset 0x418 
#define GPIO_PORTE_ICR_R				(*((volatile unsigned long *)0x4002441C)) //Offset 0x41C 
#define GPIO_PORTE_AFSEL_R			(*((volatile unsigned long *)0x40024420)) //Offset 0x420 
#define GPIO_PORTE_DR2R_R				(*((volatile unsigned long *)0x40024500)) //Offset 0x500 
#define GPIO_PORTE_DR4R_R				(*((volatile unsigned long *)0x40024504)) //Offset 0x504 
#define GPIO_PORTE_DR8R_R				(*((volatile unsigned long *)0x40024508)) //Offset 0x508 
#define GPIO_PORTE_ODR_R				(*((volatile unsigned long *)0x4002450C)) //Offset 0x50C 
#define GPIO_PORTE_PUR_R				(*((volatile unsigned long *)0x40024510)) //Offset 0x510 
#define GPIO_PORTE_PDR_R				(*((volatile unsigned long *)0x40024514)) //Offset 0x514 
#define GPIO_PORTE_SLR_R				(*((volatile unsigned long *)0x40024518)) //Offset 0x518 
#define GPIO_PORTE_DEN_R				(*((volatile unsigned long *)0x4002451C)) //Offset 0x51C 
#define GPIO_PORTE_LOCK_R				(*((volatile unsigned long *)0x40024520)) //Offset 0x520 
#define GPIO_PORTE_CR_R					(*((volatile unsigned long *)0x40024524)) //Offset 0x524 
#define GPIO_PORTE_AMSEL_R			(*((volatile unsigned long *)0x40024528)) //Offset 0x528 
#define GPIO_PORTE_PCTL_R				(*((volatile unsigned long *)0x4002452C)) //Offset 0x52C 
#define GPIO_PORTE_ADCCTL_R			(*((volatile unsigned long *)0x40024530)) //Offset 0x530 
#define GPIO_PORTE_DMACTL_R			(*((volatile unsigned long *)0x40024534)) //Offset 0x534 
#define GPIO_PORTE_PeriphID4_R	(*((volatile unsigned long *)0x40024FD0)) //Offset 0xFD0 
#define GPIO_PORTE_PeriphID5_R	(*((volatile unsigned long *)0x40024FD4)) //Offset 0xFD4 
#define GPIO_PORTE_PeriphID6_R	(*((volatile unsigned long *)0x40024FD8)) //Offset 0xFD8 
#define GPIO_PORTE_PeriphID7_R	(*((volatile unsigned long *)0x40024FDC)) //Offset 0xFDC 
#define GPIO_PORTE_PeriphID0_R	(*((volatile unsigned long *)0x40024FE0)) //Offset 0xFE0 
#define GPIO_PORTE_PeriphID1_R	(*((volatile unsigned long *)0x40024FE4)) //Offset 0xFE4 
#define GPIO_PORTE_PeriphID2_R	(*((volatile unsigned long *)0x40024FE8)) //Offset 0xFE8 
#define GPIO_PORTE_PeriphID3_R	(*((volatile unsigned long *)0x40024FEC)) //Offset 0xFEC 

//PORT E DEFINES - SWITCHES CONTROL
//---------------------------------
#define PE0_R										(*((volatile unsigned long *)0x40024004))	//From DATA register - 0x01: UNPRESSED
	
//PORT F DEFINES - REGISTERS, Base address: 0x4002.5000
//-----------------------------------------------------
#define GPIO_PORTF_DATA_R				(*((volatile unsigned long *)0x400253FC)) //Offset 0x000 
#define GPIO_PORTF_DIR_R				(*((volatile unsigned long *)0x40025400)) //Offset 0x400 
#define GPIO_PORTF_IS_R					(*((volatile unsigned long *)0x40025404)) //Offset 0x404 
#define GPIO_PORTF_IBE_R				(*((volatile unsigned long *)0x40025408)) //Offset 0x408 
#define GPIO_PORTF_IEV_R				(*((volatile unsigned long *)0x4002540C)) //Offset 0x40C 
#define GPIO_PORTF_IM_R					(*((volatile unsigned long *)0x40025410)) //Offset 0x410 
#define GPIO_PORTF_RIS_R				(*((volatile unsigned long *)0x40025414)) //Offset 0x414 
#define GPIO_PORTF_MIS_R				(*((volatile unsigned long *)0x40025418)) //Offset 0x418 
#define GPIO_PORTF_ICR_R				(*((volatile unsigned long *)0x4002541C)) //Offset 0x41C 
#define GPIO_PORTF_AFSEL_R			(*((volatile unsigned long *)0x40025420)) //Offset 0x420 
#define GPIO_PORTF_DR2R_R				(*((volatile unsigned long *)0x40025500)) //Offset 0x500 
#define GPIO_PORTF_DR4R_R				(*((volatile unsigned long *)0x40025504)) //Offset 0x504 
#define GPIO_PORTF_DR8R_R				(*((volatile unsigned long *)0x40025508)) //Offset 0x508 
#define GPIO_PORTF_ODR_R				(*((volatile unsigned long *)0x4002550C)) //Offset 0x50C 
#define GPIO_PORTF_PUR_R				(*((volatile unsigned long *)0x40025510)) //Offset 0x510 
#define GPIO_PORTF_PDR_R				(*((volatile unsigned long *)0x40025514)) //Offset 0x514 
#define GPIO_PORTF_SLR_R				(*((volatile unsigned long *)0x40025518)) //Offset 0x518 
#define GPIO_PORTF_DEN_R				(*((volatile unsigned long *)0x4002551C)) //Offset 0x51C 
#define GPIO_PORTF_LOCK_R				(*((volatile unsigned long *)0x40025520)) //Offset 0x520 
#define GPIO_PORTF_CR_R					(*((volatile unsigned long *)0x40025524)) //Offset 0x524 
#define GPIO_PORTF_AMSEL_R			(*((volatile unsigned long *)0x40025528)) //Offset 0x528 
#define GPIO_PORTF_PCTL_R				(*((volatile unsigned long *)0x4002552C)) //Offset 0x52C 
#define GPIO_PORTF_ADCCTL_R			(*((volatile unsigned long *)0x40025530)) //Offset 0x530 
#define GPIO_PORTF_DMACTL_R			(*((volatile unsigned long *)0x40025534)) //Offset 0x534 
#define GPIO_PORTF_PeriphID4_R	(*((volatile unsigned long *)0x40025FD0)) //Offset 0xFD0 
#define GPIO_PORTF_PeriphID5_R	(*((volatile unsigned long *)0x40025FD4)) //Offset 0xFD4 
#define GPIO_PORTF_PeriphID6_R	(*((volatile unsigned long *)0x40025FD8)) //Offset 0xFD8 
#define GPIO_PORTF_PeriphID7_R	(*((volatile unsigned long *)0x40025FDC)) //Offset 0xFDC 
#define GPIO_PORTF_PeriphID0_R	(*((volatile unsigned long *)0x40025FE0)) //Offset 0xFE0 
#define GPIO_PORTF_PeriphID1_R	(*((volatile unsigned long *)0x40025FE4)) //Offset 0xFE4 
#define GPIO_PORTF_PeriphID2_R	(*((volatile unsigned long *)0x40025FE8)) //Offset 0xFE8 
#define GPIO_PORTF_PeriphID3_R	(*((volatile unsigned long *)0x40025FEC)) //Offset 0xFEC 

//PORT F DEFINES - LED CONTROL
//----------------------------
#define RED_LED_R								(*((volatile unsigned long *)0x40025008))	//From DATA register - 0x02: ON
#define BLUE_LED_R							(*((volatile unsigned long *)0x40025010))	//From DATA register - 0x04: ON
#define GREEN_LED_R							(*((volatile unsigned long *)0x40025020))	//From DATA register - 0x08: ON
#define LEDS_R									(*((volatile unsigned long *)0x40025038))	//From DATA register - 0x02: RED ON, 0x04: BLUE ON, 0x08: GREEN ON

#define RED_LED_ON 							{LEDS_R 			= 0x02;}										// set PF1, clear PF2 and PF3
#define BLUE_LED_ON 						{LEDS_R 			= 0x04;}										// set PF2, clear PF1 and PF3
#define GREEN_LED_ON						{LEDS_R 			= 0x08;}										// set PF3, clear PF1 and PF2
#define PINK_LED_ON 						{LEDS_R 			= 0x06;}										// set PF1 and PF2, clear PF3
#define YELLOW_LED_ON						{LEDS_R 			= 0x0A;}										// set PF1 and PF3, clear PF2
#define SKY_LED_ON 							{LEDS_R 			= 0x0C;}										// set PF2 and PF3, clear PF1
#define WHITE_LED_ON 						{LEDS_R 			= 0x0E;}										// set PF1, PF2 and PF3
#define RED_LED_TOGGLE			 		{RED_LED_R   ^= 0x02;}										// toggle PF1
#define BLUE_LED_TOGGLE 				{BLUE_LED_R  ^= 0x04;}										// toggle PF2
#define GREEN_LED_TOGGLE			 	{GREEN_LED_R ^= 0x08;}										// toggle PF3
#define LEDS_OFF 								{LEDS_R       = 0x00;}										// clear PF1, PF2 and PF3

//PORT F DEFINES - SWITCHES CONTROL
//---------------------------------
#define PF0_R										(*((volatile unsigned long *)0x40025004))	//From DATA register - 0x01: UNPRESSED (SW2 of the LaunchPad)
#define PF4_R										(*((volatile unsigned long *)0x40025040))	//From DATA register - 0x10: UNPRESSED (SW1 of the LaunchPad)

//QEI0 DEFINES - REGISTERS, Base address: 0x4002.C000
//---------------------------------------------------
#define QEI0_QEICTL_R						(*((volatile unsigned long *)0x4002C000)) //Offset 0x000 *
#define QEI0_QEISTAT_R					(*((volatile unsigned long *)0x4002C004)) //Offset 0x004 can be used in main
#define QEI0_QEIPOS_R						(*((volatile unsigned long *)0x4002C008)) //Offset 0x008 
#define QEI0_QEIMAXPOS_R				(*((volatile unsigned long *)0x4002C00C)) //Offset 0x00C 
#define QEI0_QEILOAD_R					(*((volatile unsigned long *)0x4002C010)) //Offset 0x010 
#define QEI0_QEITIME_R					(*((volatile unsigned long *)0x4002C014)) //Offset 0x014 
#define QEI0_QEICOUNT_R					(*((volatile unsigned long *)0x4002C018)) //Offset 0x018 
#define QEI0_QEISPEED_R					(*((volatile unsigned long *)0x4002C01C)) //Offset 0x01C 
#define QEI0_QEIINTEN_R					(*((volatile unsigned long *)0x4002C020)) //Offset 0x020 
#define QEI0_QEIRIS_R						(*((volatile unsigned long *)0x4002C024)) //Offset 0x024 
#define QEI0_QEIISC_R						(*((volatile unsigned long *)0x4002C028)) //Offset 0x028 

// TO TEST
// filter is enabled by the FILTEN bit in the QEI Control (QEICTL) register
// The frequency of the input update is programmable using the FILTCNT bit field in the QEICTL register.
// SIGMODE bit to be cleared on the QEICTL register (quadrature phase mode)
// reset mode of counter is determined by the RESMODE bit of the QEICTL register.
// The edge count from the previous time period is available to the controller via the QEI Velocity (QEISPEED) register
// while the edge count for the current time period is being accumulated in the QEI Velocity Counter (QEICOUNT) register
// The period of the timer is configurable by specifying the load value for the timer in the QEI Timer Load (QEILOAD) register
// capture mode set in the QEICTL register (2 for CAPMODE clear and 4 for CAPMODE set)
// PAS COMPRIS: Important: Reducing constant factors at compile time is the best way to control the intermediate values of this equation and reduce the processing requirement of computing this equation.
// interrupt on several events: phase error, direction change, reception of the index pulse, and expiration of the velocity timer

//QEI1 DEFINES - REGISTERS, Base address: 0x4002.D000
//---------------------------------------------------
#define QEI1_QEICTL_R						(*((volatile unsigned long *)0x4002D000)) //Offset 0x000  
#define QEI1_QEISTAT_R					(*((volatile unsigned long *)0x4002D004)) //Offset 0x004
#define QEI1_QEIPOS_R						(*((volatile unsigned long *)0x4002D008)) //Offset 0x008
#define QEI1_QEIMAXPOS_R				(*((volatile unsigned long *)0x4002D00C)) //Offset 0x00C
#define QEI1_QEILOAD_R					(*((volatile unsigned long *)0x4002D010)) //Offset 0x010
#define QEI1_QEITIME_R					(*((volatile unsigned long *)0x4002D014)) //Offset 0x014
#define QEI1_QEICOUNT_R					(*((volatile unsigned long *)0x4002D018)) //Offset 0x018
#define QEI1_QEISPEED_R					(*((volatile unsigned long *)0x4002D01C)) //Offset 0x01C
#define QEI1_QEIINTEN_R					(*((volatile unsigned long *)0x4002D020)) //Offset 0x020
#define QEI1_QEIRIS_R						(*((volatile unsigned long *)0x4002D024)) //Offset 0x024
#define QEI1_QEIISC_R						(*((volatile unsigned long *)0x4002D028)) //Offset 0x028

/*
//NVIC DEFINES - REGISTERS, Base address: 0xE000.E000
//---------------------------------------------------
#define NVIC_EN0_R							(*((volatile unsigned long *)0xE000E100)) 
#define NVIC_EN1_R							(*((volatile unsigned long *)0xE000E104)) 
#define NVIC_EN2_R							(*((volatile unsigned long *)0xE000E108)) 
#define NVIC_EN3_R							(*((volatile unsigned long *)0xE000E10C)) 
#define NVIC_EN4_R							(*((volatile unsigned long *)0xE000E110)) 
#define NVIC_DIS0_R							(*((volatile unsigned long *)0xE000E180)) 
#define NVIC_DIS1_R							(*((volatile unsigned long *)0xE000E184)) 
#define NVIC_DIS2_R							(*((volatile unsigned long *)0xE000E188)) 
#define NVIC_DIS3_R							(*((volatile unsigned long *)0xE000E18C)) 
#define NVIC_DIS4_R							(*((volatile unsigned long *)0xE000E190)) 
#define NVIC_PEND0_R						(*((volatile unsigned long *)0xE000E200)) 
#define NVIC_PEND1_R						(*((volatile unsigned long *)0xE000E204)) 
#define NVIC_PEND2_R						(*((volatile unsigned long *)0xE000E208)) 
#define NVIC_PEND3_R						(*((volatile unsigned long *)0xE000E20C)) 
#define NVIC_PEND4_R						(*((volatile unsigned long *)0xE000E210)) 
#define NVIC_UNPEND0_R					(*((volatile unsigned long *)0xE000E280)) 
#define NVIC_UNPEND1_R					(*((volatile unsigned long *)0xE000E284)) 
#define NVIC_UNPEND2_R					(*((volatile unsigned long *)0xE000E288)) 
#define NVIC_UNPEND3_R					(*((volatile unsigned long *)0xE000E28C)) 
#define NVIC_UNPEND4_R					(*((volatile unsigned long *)0xE000E290) 
#define NVIC_ACTIVE0_R					(*((volatile unsigned long *)0xE000E300)) 
#define NVIC_ACTIVE1_R					(*((volatile unsigned long *)0xE000E304)) 
#define NVIC_ACTIVE2_R					(*((volatile unsigned long *)0xE000E308)) 
#define NVIC_ACTIVE3_R					(*((volatile unsigned long *)0xE000E30C)) 
#define NVIC_ACTIVE4_R					(*((volatile unsigned long *)0xE000E310)) 
#define NVIC_PRI0_R							(*((volatile unsigned long *)0xE000E400)) 
#define NVIC_PRI1_R							(*((volatile unsigned long *)0xE000E404)) 
#define NVIC_PRI2_R							(*((volatile unsigned long *)0xE000E408)) 
#define NVIC_PRI3_R							(*((volatile unsigned long *)0xE000E40C)) 
#define NVIC_PRI4_R							(*((volatile unsigned long *)0xE000E410)) 
#define NVIC_PRI5_R							(*((volatile unsigned long *)0xE000E414)) 
#define NVIC_PRI6_R							(*((volatile unsigned long *)0xE000E418)) 
#define NVIC_PRI7_R							(*((volatile unsigned long *)0xE000E41C)) 
#define NVIC_PRI8_R							(*((volatile unsigned long *)0xE000E420)) 
#define NVIC_PRI9_R							(*((volatile unsigned long *)0xE000E424)) 
#define NVIC_PRI10_R						(*((volatile unsigned long *)0xE000E428)) 
#define NVIC_PRI11_R						(*((volatile unsigned long *)0xE000E42C)) 
#define NVIC_PRI12_R						(*((volatile unsigned long *)0xE000E430)) 
#define NVIC_PRI13_R						(*((volatile unsigned long *)0xE000E434)) 
#define NVIC_PRI14_R						(*((volatile unsigned long *)0xE000E438)) 
#define NVIC_PRI15_R						(*((volatile unsigned long *)0xE000E43C)) 
#define NVIC_PRI16_R						(*((volatile unsigned long *)0xE000E440)) 
#define NVIC_PRI17_R						(*((volatile unsigned long *)0xE000E444)) 
#define NVIC_PRI18_R						(*((volatile unsigned long *)0xE000E448)) 
#define NVIC_PRI19_R						(*((volatile unsigned long *)0xE000E44C)) 
#define NVIC_PRI20_R						(*((volatile unsigned long *)0xE000E450)) 
#define NVIC_PRI21_R						(*((volatile unsigned long *)0xE000E454)) 
#define NVIC_PRI22_R						(*((volatile unsigned long *)0xE000E458)) 
#define NVIC_PRI23_R						(*((volatile unsigned long *)0xE000E45C)) 
#define NVIC_PRI24_R						(*((volatile unsigned long *)0xE000E460)) 
#define NVIC_PRI25_R						(*((volatile unsigned long *)0xE000E464)) 
#define NVIC_PRI26_R						(*((volatile unsigned long *)0xE000E468)) 
#define NVIC_PRI27_R						(*((volatile unsigned long *)0xE000E46C)) 
#define NVIC_PRI28_R						(*((volatile unsigned long *)0xE000E470)) 
#define NVIC_PRI29_R						(*((volatile unsigned long *)0xE000E474)) 
#define NVIC_PRI30_R						(*((volatile unsigned long *)0xE000E478)) 
#define NVIC_PRI31_R						(*((volatile unsigned long *)0xE000E47C)) 
#define NVIC_PRI32_R						(*((volatile unsigned long *)0xE000E480)) 
#define NVIC_PRI33_R						(*((volatile unsigned long *)0xE000E484)) 
#define NVIC_PRI34_R						(*((volatile unsigned long *)0xE000E488)) 
#define NVIC_SWTRIG_R						(*((volatile unsigned long *)0xE000EF00)) */

//------------PORT C------------
// Initialize the PORT C for QEI1 (Quadrature Encoder Interface)
// ...
// Input: none
// Output: none
void PORTC_Init(void);

//------------PORT E------------
// Initialize the PORT E
// GPIO ; Digital ; PE0 and PE4 input with pull-up resistors ; PE1 to PE3 output
// Input: none
// Output: none
void PORTE_Init(void);

//------------PORT F------------
// Initialize the PORT F
// GPIO ; Digital ; PF0 and PF4 input with pull-up resistors ; PF1 to PF3 output
// Input: none
// Output: none
void PORTF_Init(void);

//------------PORT F------------
// Initialize the PORT F enabling interrupt on PF4 (digital input)
// 
// Input: none
// Output: none
void PORTF_InterruptInit(void);

//------------SYSTICK------------
// Initialize the Timer SYSTICK with interrupt
// 
// Input: none
// Output: none
void SysTick_InterruptInit(void);

//------------PLL------------
// Set the µC clock to 80MHz using the PLL
// 
// Input: none
// Output: none
void PLL_Init(void);

//------------DELAY------------
// Delay function expressed ticks
// 
// Input: delay in tick
// Output: none
void delay_ticks(unsigned long nticks);

//------------DELAY------------
// Delay function expressed in ms using SysTick
// 
// Input: delay in ms
// Output: none
void delay_ms(unsigned long nms);

void DisableInterrupts(void); // Disable interrupts
void EnableInterrupts(void);  // Enable interrupts
long StartCritical (void);    // previous I bit, disable interrupts
void EndCritical(long sr);    // restore I bit to previous value
void WaitForInterrupt(void);  // low power mode
